FROM python:3.12-slim

WORKDIR /app

COPY ./src/meetings_data_scraper.py /app/main.py
COPY ./src/consts.py /app/
COPY ./data_scrapper_requirements.txt /app/requirements.txt
COPY ./.env.docker.dev /.env.dev

RUN apt-get update && apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python", "main.py"]